### ISSUE TITLE
Solutions Branch

### ISSUE THREAD

**Issue by jdbean** [learn-co-curriculum/react-events-in-detail#6]
This lab lacks a solution.

**Comment by PeterBell** [comment]
Hi @jdbean 

Thanks so much for the comment! This is a readme, not a lab. As such it isn't supposed to have a solution branch.

Thanks!
Peter

**Comment by jdbean** [comment]
Oops! Must have submitted to the wrong repo I guess. Thanks a bunch! Sorry
for the false alarm.
